export const mockWeatherData = {
  Mumbai: {
    location: {
      name: 'Mumbai',
      region: 'Maharashtra',
      country: 'India',
      lat: 19.07,
      lon: 72.88,
    },
    current: {
      last_updated: new Date().toISOString(),
      temp_c: 28,
      temp_f: 82,
      condition: {
        text: 'Partly cloudy',
        code: 1003,
      },
      wind_kph: 20,
      wind_mph: 12,
      humidity: 75,
      cloud: 50,
      feelslike_c: 31,
      feelslike_f: 88,
      vis_km: 10,
      vis_miles: 6,
      uv: 7,
      pressure_mb: 1008,
      wind_dir: 'SW',
    },
  },
  Delhi: {
    location: {
      name: 'Delhi',
      region: 'Delhi',
      country: 'India',
      lat: 28.67,
      lon: 77.22,
    },
    current: {
      last_updated: new Date().toISOString(),
      temp_c: 32,
      temp_f: 90,
      condition: {
        text: 'Sunny',
        code: 1000,
      },
      wind_kph: 15,
      wind_mph: 9,
      humidity: 45,
      cloud: 10,
      feelslike_c: 35,
      feelslike_f: 95,
      vis_km: 10,
      vis_miles: 6,
      uv: 8,
      pressure_mb: 1010,
      wind_dir: 'NW',
    },
  },
  Bangalore: {
    location: {
      name: 'Bangalore',
      region: 'Karnataka',
      country: 'India',
      lat: 12.97,
      lon: 77.59,
    },
    current: {
      last_updated: new Date().toISOString(),
      temp_c: 24,
      temp_f: 75,
      condition: {
        text: 'Partly cloudy',
        code: 1003,
      },
      wind_kph: 12,
      wind_mph: 7,
      humidity: 65,
      cloud: 40,
      feelslike_c: 25,
      feelslike_f: 77,
      vis_km: 10,
      vis_miles: 6,
      uv: 6,
      pressure_mb: 1012,
      wind_dir: 'W',
    },
  },
  Hyderabad: {
    location: {
      name: 'Hyderabad',
      region: 'Telangana',
      country: 'India',
      lat: 17.38,
      lon: 78.47,
    },
    current: {
      last_updated: new Date().toISOString(),
      temp_c: 29,
      temp_f: 84,
      condition: {
        text: 'Clear',
        code: 1000,
      },
      wind_kph: 14,
      wind_mph: 9,
      humidity: 55,
      cloud: 5,
      feelslike_c: 30,
      feelslike_f: 86,
      vis_km: 10,
      vis_miles: 6,
      uv: 7,
      pressure_mb: 1011,
      wind_dir: 'SE',
    },
  },
  Chennai: {
    location: {
      name: 'Chennai',
      region: 'Tamil Nadu',
      country: 'India',
      lat: 13.08,
      lon: 80.27,
    },
    current: {
      last_updated: new Date().toISOString(),
      temp_c: 30,
      temp_f: 86,
      condition: {
        text: 'Sunny',
        code: 1000,
      },
      wind_kph: 18,
      wind_mph: 11,
      humidity: 70,
      cloud: 15,
      feelslike_c: 33,
      feelslike_f: 91,
      vis_km: 10,
      vis_miles: 6,
      uv: 8,
      pressure_mb: 1009,
      wind_dir: 'SE',
    },
  },
  Kolkata: {
    location: {
      name: 'Kolkata',
      region: 'West Bengal',
      country: 'India',
      lat: 22.57,
      lon: 88.36,
    },
    current: {
      last_updated: new Date().toISOString(),
      temp_c: 27,
      temp_f: 81,
      condition: {
        text: 'Partly cloudy',
        code: 1003,
      },
      wind_kph: 16,
      wind_mph: 10,
      humidity: 80,
      cloud: 45,
      feelslike_c: 30,
      feelslike_f: 86,
      vis_km: 10,
      vis_miles: 6,
      uv: 6,
      pressure_mb: 1010,
      wind_dir: 'S',
    },
  },
  Pune: {
    location: {
      name: 'Pune',
      region: 'Maharashtra',
      country: 'India',
      lat: 18.52,
      lon: 73.86,
    },
    current: {
      last_updated: new Date().toISOString(),
      temp_c: 26,
      temp_f: 79,
      condition: {
        text: 'Partly cloudy',
        code: 1003,
      },
      wind_kph: 13,
      wind_mph: 8,
      humidity: 60,
      cloud: 35,
      feelslike_c: 27,
      feelslike_f: 81,
      vis_km: 10,
      vis_miles: 6,
      uv: 7,
      pressure_mb: 1011,
      wind_dir: 'W',
    },
  },
  Ahmedabad: {
    location: {
      name: 'Ahmedabad',
      region: 'Gujarat',
      country: 'India',
      lat: 23.02,
      lon: 72.57,
    },
    current: {
      last_updated: new Date().toISOString(),
      temp_c: 31,
      temp_f: 88,
      condition: {
        text: 'Sunny',
        code: 1000,
      },
      wind_kph: 17,
      wind_mph: 11,
      humidity: 40,
      cloud: 5,
      feelslike_c: 33,
      feelslike_f: 91,
      vis_km: 10,
      vis_miles: 6,
      uv: 8,
      pressure_mb: 1012,
      wind_dir: 'NW',
    },
  },
  Jaipur: {
    location: {
      name: 'Jaipur',
      region: 'Rajasthan',
      country: 'India',
      lat: 26.92,
      lon: 75.82,
    },
    current: {
      last_updated: new Date().toISOString(),
      temp_c: 33,
      temp_f: 91,
      condition: {
        text: 'Clear',
        code: 1000,
      },
      wind_kph: 14,
      wind_mph: 9,
      humidity: 35,
      cloud: 0,
      feelslike_c: 35,
      feelslike_f: 95,
      vis_km: 10,
      vis_miles: 6,
      uv: 9,
      pressure_mb: 1011,
      wind_dir: 'W',
    },
  },
  Surat: {
    location: {
      name: 'Surat',
      region: 'Gujarat',
      country: 'India',
      lat: 21.17,
      lon: 72.83,
    },
    current: {
      last_updated: new Date().toISOString(),
      temp_c: 29,
      temp_f: 84,
      condition: {
        text: 'Partly cloudy',
        code: 1003,
      },
      wind_kph: 18,
      wind_mph: 11,
      humidity: 65,
      cloud: 40,
      feelslike_c: 31,
      feelslike_f: 88,
      vis_km: 10,
      vis_miles: 6,
      uv: 7,
      pressure_mb: 1010,
      wind_dir: 'SW',
    },
  },
  // Keep London, New York, Tokyo for search functionality
  London: {
    location: {
      name: 'London',
      region: 'City of London, Greater London',
      country: 'United Kingdom',
      lat: 51.52,
      lon: -0.11,
    },
    current: {
      last_updated: new Date().toISOString(),
      temp_c: 15,
      temp_f: 59,
      condition: {
        text: 'Partly cloudy',
        code: 1003,
      },
      wind_kph: 13,
      wind_mph: 8,
      humidity: 72,
      cloud: 75,
      feelslike_c: 14,
      feelslike_f: 57,
      vis_km: 10,
      vis_miles: 6,
      uv: 3,
      pressure_mb: 1013,
      wind_dir: 'SW',
    },
  },
};

export const mockSearchResults = [
  { name: 'Mumbai', region: 'Maharashtra', country: 'India' },
  { name: 'Delhi', region: 'Delhi', country: 'India' },
  { name: 'Bangalore', region: 'Karnataka', country: 'India' },
  { name: 'Hyderabad', region: 'Telangana', country: 'India' },
  { name: 'Chennai', region: 'Tamil Nadu', country: 'India' },
  { name: 'Kolkata', region: 'West Bengal', country: 'India' },
  { name: 'Pune', region: 'Maharashtra', country: 'India' },
];
